import { I18NResource } from '~/lib/utils'
import colors from '~/theme/colors'

export const STATUS_DESCRIPTION: Record<number, I18NResource> = {
  0: "wallet.pending",
  1: "wallet.passed",
  2: "wallet.rejected",
  3: "wallet.successful",
  4: "wallet.failed",
  5: "wallet.returned",
  6: "wallet.cardPendingPayment",
  7: "wallet.usdtPendingPayment",
  8: "wallet.orderCancelled",
  9: "wallet.gbkydPendingPayment",
  10: "wallet.paymentSubmitted",
  100: "wallet.thirdPartyPendingPayment",
}

export const CHANNEL_DESCRIPTION: Record<number, I18NResource> = {
  0: "wallet.trc20",
  1: "wallet.bep20",
  3: "wallet.bank",
  4: "wallet.bitexpress",
  5: "wallet.gbkyd",
  6: "wallet.zjbyk",
  7: "wallet.hntwq",
  10: "wallet.recharge",
  11: "wallet.reissue",
  12: "wallet.deduction",
  101: "wallet.thirdParty",
  102: "wallet.usdtTransfer",
  103: "wallet.systemRecharge",
}

export const OPERATION_DESCRIPTION: Record<number, I18NResource> = {
  0: "wallet.deposit",
  1: "wallet.withdraw",
  2: "wallet.dailySettlement",
  5: "wallet.marginFreeze",
  6: "wallet.closeProfitLoss",
  7: "wallet.commissionFee",
  9: "wallet.marginReturn",
  10: "wallet.overnightFee",
  11: "wallet.couponDeduction",
  12: "wallet.pendingOrderMarginFreeze",
  20: "wallet.platformCommissionFee",
  21: "wallet.centerCommissionFee",
  22: "wallet.agentCommissionFee",
  23: "wallet.platformTradeProfitShare",
  24: "wallet.centerTradeProfitShare",
  25: "wallet.inviteFriendRefund",
  26: "wallet.traderRebate",
  27: "wallet.traderWithdraw",
  28: "wallet.firstInvite",
  29: "wallet.friendDailyTrades",
  30: "wallet.systemDeposit",
  31: "wallet.systemDeduction",
  32: "wallet.commissionReissue",
  40: "wallet.withdrawFailed",
  41: "wallet.bonus",
  42: "wallet.bonusDeduction",
  43: "wallet.friendDepositBonus",
  50: "wallet.coinExchange",
  51: "wallet.traderRebateIncome",
  52: "wallet.optionBuy",
  53: "wallet.optionSellProfit",
  54: "wallet.fundPurchase",
  55: "wallet.fundRedeem",
  56: "wallet.fundDeposit",
  57: "wallet.fundWithdraw",
  58: "wallet.fundProfitSettlement",
  59: "wallet.fundProfitDeposit",
  60: "wallet.commissionSettlement",
  61: "wallet.fundPurchaseRefund",
  62: "wallet.fundPurchaseFreeze",
  63: "wallet.fundPurchaseFreezeDeposit",
  64: "wallet.fundPurchaseFreezeReturn",
  70: "wallet.fundProfitSystemDeposit",
  71: "wallet.fundProfitSystemWithdraw",
  75: "wallet.systemCommissionDeposit",
  76: "wallet.systemCommissionWithdraw",
  77: "wallet.closeProfit",
  78: "wallet.closeLoss",
  101: "wallet.fundPurchaseFee",
  102: "wallet.fundPurchaseFeeDeposit",
  103: "wallet.fundRedeemFee",
  104: "wallet.fundRedeemFeeDeposit",
  106: "wallet.fundPurchaseFeeRefundReturn",
  1001: "wallet.systemBalanceDeposit",
  1002: "wallet.systemBalanceWithdraw",
  1003: "wallet.systemGuessDeposit",
  1004: "wallet.systemGuessWithdraw",
  1005: "wallet.systemCloseDeposit",
  1006: "wallet.systemCloseWithdraw",
  5001: "wallet.fundFromMainWallet",
  5002: "wallet.fundToMainWallet",
  5003: "wallet.fundFromOptionWallet",
  5004: "wallet.fundToOptionWallet",
  5005: "wallet.fundFromForexWallet",
  5006: "wallet.fundToForexWallet",
  5007: "wallet.fundSubscriptionDeduction",
  5008: "wallet.fundSubscriptionFee",
  5009: "wallet.fundSubscriptionRefund",
  5010: "wallet.fundSubscriptionFeeRefund",
  5011: "wallet.fundRedeemDeposit",
  5012: "wallet.fundRedeemFee",
  5013: "wallet.fundProfitSettlementDeduction",
  5014: "wallet.fundProfitDeposit",
  5015: "wallet.fundSubscriptionTransfer",
  5017: "wallet.fundRedeemTransfer",
  6001: "wallet.forexFromMainWallet",
  6002: "wallet.forexToMainWallet",
  6007: "wallet.forexCloseProfit",
  6008: "wallet.forexCloseLoss",
  7001: "wallet.optionFromMainWallet",
  7002: "wallet.optionToMainWallet",
  7003: "wallet.optionFromForexWallet",
  7004: "wallet.optionToForexWallet",
  7005: "wallet.optionFromFundWallet",
  7006: "wallet.optionToFundWallet",
  7007: "wallet.optionProfit",
  7008: "wallet.optionMargin",
  8007: "wallet.commissionReissueDeposit",
  8008: "wallet.commissionSettlementDeposit",
  8011: "wallet.mainWalletForexProfit",
  8012: "wallet.mainWalletForexLoss",
  8013: "wallet.referralReward",
  8014: "wallet.teamReward",
  8015: "wallet.peerReward",
  8016: "wallet.kycBonus",
  8017: "wallet.depositBonus",
  8021: "wallet.giftCardPurchase",
  9001: "wallet.deposit",
  9002: "wallet.withdraw",
  9003: "wallet.withdrawFee",
  9004: "wallet.adminDeposit",
  9005: "wallet.adminDeduction",
  9006: "wallet.withdrawReturn",
}

export const getStatusColor = (status: number) => {
  switch (status) {
    case 0:
    case 6:
    case 7:
    case 9:
    case 100:
      return colors.warning
    case 1:
    case 3:
      return colors.primary
    case 2:
    case 4:
      return colors.destructive
    default:
      return colors.secondary
  }
}
