export { default as home } from "~/assets/images/icon/home.svg"
export { default as partner } from "~/assets/images/icon/partner.svg"
export { default as positions } from "~/assets/images/icon/positions.svg"
export { default as trade } from "~/assets/images/icon/trade.svg"
export { default as wallet } from "~/assets/images/icon/wallet.svg"
